import Home from "./home/Home"
import Head from "next/head"

export default function AppHome() {
  return (
    <>
      <Head>
        <title>JOBS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cat2.png" />
      </Head>
      <Home/>
    </>
  )
}
